#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run commitlint with npx (no need for install)
npx --no-install commitlint --edit $1

# Section for git-secrets
GIT_SECRETS_PATH=$(which git-secrets 2>/dev/null)

if [ ! -x "$GIT_SECRETS_PATH" ]; then
    echo "git-secrets is not installed. Please run 'brew install git-secrets' or visit https://github.com/awslabs/git-secrets#installing-git-secrets"
    exit 1
fi

echo "Using git-secrets at: $GIT_SECRETS_PATH"

# Initialise git-secrets configuration
$GIT_SECRETS_PATH --register-aws > /dev/null

echo "Running git-secrets..."
# Scans the commit message
$GIT_SECRETS_PATH --commit_msg_hook -- "$@"
